apiVersion: apps/v1
kind: Deployment
metadata:
  name: platsrv-registry-web
spec:
  template:
    spec:
      containers:
        - name: platsrv-registry-web
          env:
            - name: REACT_APP_SSO_URL
              value: https://dev.oidc.gov.bc.ca/auth/
            - name: REACT_APP_SSO_REALM
              value: "devhub"
            - name: REACT_APP_SSO_CLIENT_ID
              value: "registry-web"
            - name: REACT_APP_API_URL
              value: https://registry-new-api-platform-registry-dev.apps.silver.devops.gov.bc.ca/graphql